#!/usr/bin/env bash
# Python module metadata for EnvSwitch.

ENVS_PYTHON_DEFAULT_VERSION="${ENVS_PYTHON_DEFAULT_VERSION:-3.12.12}"
ENVS_PYTHON_STANDALONE_RELEASE="${ENVS_PYTHON_STANDALONE_RELEASE:-20260211}"
